.\" -*- nroff -*-
.\" Copyright (C) 2014 Ollie Etherington
.\"
.\" This document is licensed under the terms of The GNU Free Documentation
.\" License, as published by the Free Software Foundation, version 1.2 or
.\" (at your option) any later version, with no Invariant Sections, no
.\" Front-Cover Texts, and no Back-Cover Texts.  You should have received a
.\" copy of the GNU Free Documentation License along with this program.  If
.\" not, see <http://www.gnu.org/licenses/>.
.\"
.\" Update the date below whenever revising:
.TH WS 1 "15 December 2014" "Version 0.1.1"

.SH NAME
ws - A lightweight workspace manager

.SH SYNOPSIS
.B ws
.I [OPTIONS]\ [WORKSPACE NAME]
.br

.SH DESCRIPTION
This manual page briefly documents the \fBws\fP command.
.PP
\fBws\fP is a free lightweight workspace manager for use on systems running
Bash with configuration for editor invocation and support for multiple
workspace definitions per directory.
.PP
Global configuration is done in the \fIwsrc\fP file described in detail in it's
own manpage; \fBwsrc\fP(5).
.PP
Workspaces are defined in directory specific files called \fI.ws\fP. Their
syntax is described below in the section entitled \fIwriting a .ws file\fP.

.SH OPTIONS
.TP
.B \-e (\-\-edit)
Edit (or create) the .ws configuration file for the current directory.
.TP
.B \-p (\-\-print)
Instead of running the final editor command, print it to stdout instead.
.TP
.B \-h (\-\-help)
Display a help message specifying command line usage.
.TP
.B \-v (\-\-version)
Display program version information.

.SH WRITING A .WS FILE
Workspaces a defined at the directory level in a file called \fI.ws\fP.
Invoking \fBws\fP in a directory without providing a workspace name on the
command line will open the default workspace which is, by default, called
\fBws\fP. It is defined like so:
.PP
\fBws { MY_FILE_1 MY_FILE_2 }\fP
.PP
Note that whitespace is syntactically unimportant - this definition could have
been split over several lines for easier reading and editing.
.PP
In the event that multiple workspaces in the same directory are given the same
name, the FIRST definition will always be launched.
.PP
Normally workspaces use the default editor command which can be set in the
wsrc configuration file but it's also possible to give workspaces their own
custom editor commands. This is done with the following syntax:
.PP
\fBws - "nano --mouse" { MY_FILE_1 }\fP
.PP
This will invoke the command "nano --mouse MY_FILE_1". Note that the whitespace
either side of the hyphen is necessary otherwise it will be interpreted as a
workspace name with a dash in it. Single word commands such as "nano" or
"emacs" don't require quotes but any command with whitespace in does to avoid
ambiguity.

.SH BUGS
Please send any comments or bug reports to \fBojay@ojay.co.uk\fP.

.SH HOMEPAGE
https://github.com/o-jay/ws

.SH SEE ALSO
.PD 0
.TP
\fBwsrc\fP(5)

.SH AUTHOR
Ollie Etherington <ojay@ojay.co.uk>.
.PP
This document is available under the terms of the GNU Free Documentation
License.
